spring.application.name=pesquera

spring.datasource.url=jdbc:postgresql://localhost:5432/pesquera
spring.datasource.username=postgres
spring.datasource.password=alex123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect