spring.application.name=pesquera

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pesqueraVA3}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Configuración JWT
jwt.secret=${JWT_SECRET:}

# Credenciales por defecto
app.default.gerente.username=${DEFAULT_GERENTE_USER:gerente_general}
app.default.gerente.password=${DEFAULT_GERENTE_PASS:pota2026}
app.default.supervisor.username=${DEFAULT_SUPERVISOR_USER:supervisor_planta}
app.default.supervisor.password=${DEFAULT_SUPERVISOR_PASS:planta2026}
